#!/usr/bin/env sh
set -eu

# Upload Android app
UPLOAD_PATH="gs://mobile.dev/cli_e2e"

cd build/app/outputs/flutter-apk
cp app-debug.apk demo_app.apk
cd -

gsutil cp build/app/outputs/flutter-apk/demo_app.apk "$UPLOAD_PATH/demo_app.apk"
gsutil acl ch -r -u AllUsers:R "$UPLOAD_PATH/demo_app.apk"

# Upload iOS app
cd build/ios/iphonesimulator
cp Runner.app demo_app.app
cd demo_app.app

zip -r -q ../demo_app.zip . -x "/**/.*" -x "__MACOSX"

cd ..
cd ../../../

gsutil cp build/ios/iphonesimulator/demo_app.zip "$UPLOAD_PATH/demo_app.zip"
gsutil acl ch -r -u AllUsers:R "$UPLOAD_PATH/demo_app.zip"
